"""Pipeline orchestrator — manages multi-stage project generation.

Each stage runs as an independent background task. The orchestrator
tracks dependencies and submits the next eligible stages as workers
complete.
"""
from __future__ import annotations

import logging
from concurrent.futures import ThreadPoolExecutor

from . import repository

logger = logging.getLogger(__name__)

executor = ThreadPoolExecutor(max_workers=4, thread_name_prefix="pipeline")

# Dependency graph: stage -> list of stages that must complete first
STAGE_DEPS: dict[str, list[str]] = {
    "generate_story": [],
    "generate_characters": ["generate_story"],
}

ALL_STAGES = list(STAGE_DEPS.keys())


def start_pipeline(project_id: int) -> int:
    """Start a full pipeline for a new project."""
    repository.fail_project_running_tasks(project_id, "Superseded by new pipeline run.")
    repository.update_project_status(project_id, "draft")

    parent_task_id = repository.create_task(
        project_id=project_id,
        task_type="pipeline",
        params={"stages": ALL_STAGES},
    )
    executor.submit(_run_pipeline, project_id, parent_task_id, ALL_STAGES)
    return parent_task_id


def start_rewrite_pipeline(project_id: int) -> int:
    """Start a pipeline for a project created by rewrite (story already done)."""
    repository.fail_project_running_tasks(project_id, "Superseded by new pipeline run.")

    # Story is already generated by rewrite_story_for_project(), skip it
    remaining = [s for s in ALL_STAGES if s != "generate_story"]
    skip_stages = {"generate_story"}
    parent_task_id = repository.create_task(
        project_id=project_id,
        task_type="pipeline",
        params={"stages": remaining, "skip_story": True, "skip_stages": list(skip_stages)},
    )
    executor.submit(_run_pipeline, project_id, parent_task_id, remaining, skip_stages=skip_stages)
    return parent_task_id


def start_from_stage(project_id: int, from_stage: str) -> int:
    """Start a partial pipeline from a specific stage.

    from_stage uses pipeline names (e.g. "generate_beats").
    """
    # Map pipeline stage names to the short names used by invalidate_downstream
    _stage_short = {
        "generate_story": "story",
        "generate_characters": "characters",
    }
    repository.invalidate_downstream(project_id, _stage_short.get(from_stage, from_stage))

    # Build stage list: from_stage + all stages that transitively depend on it
    stages_to_run = _get_downstream_stages(from_stage)

    skip_stages = set(ALL_STAGES) - set(stages_to_run)
    parent_task_id = repository.create_task(
        project_id=project_id,
        task_type="pipeline",
        params={"stages": stages_to_run, "from_stage": from_stage, "skip_stages": list(skip_stages)},
    )
    executor.submit(_run_pipeline, project_id, parent_task_id, stages_to_run, skip_stages=skip_stages)
    return parent_task_id


def on_stage_complete(parent_task_id: int) -> None:
    """Called by a worker task when it finishes. Advances the pipeline."""
    task = repository.get_task(parent_task_id)
    if not task or task["status"] not in ("queued", "running"):
        return
    project_id = task["project_id"]
    # Read skip_stages from persisted params so subsequent calls remember them
    import json as _json
    params = _json.loads(task.get("params") or "{}")
    skip_stages = set(params.get("skip_stages", []))
    executor.submit(_advance_pipeline, project_id, parent_task_id, skip_stages=skip_stages)


def _get_downstream_stages(from_stage: str) -> list[str]:
    """Get all stages that depend (transitively) on from_stage, inclusive."""
    result = []
    visited = set()

    def visit(stage: str):
        if stage in visited:
            return
        visited.add(stage)
        result.append(stage)
        for other, deps in STAGE_DEPS.items():
            if stage in deps:
                visit(other)

    visit(from_stage)
    return result


def _run_pipeline(project_id: int, parent_task_id: int, stages: list[str], skip_stages: set[str] | None = None) -> None:
    """Entry point for a pipeline run. Submits initial eligible stages."""
    skip_stages = skip_stages or set()
    repository.update_task(parent_task_id, "running")
    _advance_pipeline(project_id, parent_task_id, skip_stages=skip_stages)


def _advance_pipeline(project_id: int, parent_task_id: int, skip_stages: set[str] | None = None) -> None:
    """Core scheduler: check completed stages, submit next eligible ones."""
    skip_stages = skip_stages or set()

    # Build status map from child tasks
    children = repository.get_child_tasks(parent_task_id)
    stage_status: dict[str, str] = {}
    for child in children:
        stage_status[child["task_type"]] = child["status"]

    # Check for failures
    for stage, status in stage_status.items():
        if status == "failed":
            repository.update_task(parent_task_id, "failed", f"Stage '{stage}' failed.")
            return

    # Find eligible stages: not yet submitted, all deps satisfied
    newly_submitted = []
    for stage in ALL_STAGES:
        if stage in skip_stages:
            continue
        if stage in stage_status:
            continue  # already submitted
        deps = STAGE_DEPS[stage]
        deps_met = all(
            dep in skip_stages or stage_status.get(dep) == "succeeded"
            for dep in deps
        )
        if deps_met:
            task_id = repository.create_task(
                project_id=project_id,
                task_type=stage,
                parent_task_id=parent_task_id,
            )
            _submit_worker(task_id, project_id, stage, parent_task_id)
            stage_status[stage] = "queued"
            newly_submitted.append(stage)

    if not newly_submitted:
        # Check if all stages are done
        all_done = all(
            stage in skip_stages or stage_status.get(stage) == "succeeded"
            for stage in ALL_STAGES
        )
        if all_done:
            repository.update_task(parent_task_id, "succeeded")


def _submit_worker(task_id: int, project_id: int, stage: str, parent_task_id: int) -> None:
    """Submit a worker task to the thread pool."""
    from . import services  # deferred to avoid circular import

    def run():
        repository.update_task(task_id, "running")
        try:
            _heartbeat = lambda: repository.touch_task(task_id)
            _heartbeat()

            if stage == "generate_story":
                services.generate_story(project_id)
            elif stage == "generate_characters":
                services.generate_characters(project_id)
            else:
                raise ValueError(f"Unknown stage: {stage}")

            repository.update_task(task_id, "succeeded")
            on_stage_complete(parent_task_id)
        except Exception as exc:
            logger.exception("Pipeline stage '%s' failed for project %s", stage, project_id)
            repository.update_task(task_id, "failed", str(exc))
            on_stage_complete(parent_task_id)

    executor.submit(run)
